Dev Department Official Statement Regarding Prop 349
CosmosContracts/council pull request #40
Opened 2024-05-10 19:08 UTC by rayraspberry

Draft of Statement Regarding Proposal 349

2024-05-10 21:37 UTC, poroburu requested changes, later dismissed
```suggestion
Charter```

2024-05-10 21:39 UTC, poroburu commented
Sorry, working on my IDE PR code review workflow. It might be a little odd until I figure it out.

2024-05-10 21:49 UTC, kopeboy commented
I see no changes @poroburu, are you about to make them?

2024-05-10 22:15 UTC, poroburu commented
> I see no changes @poroburu, are you about to make them?

No changes were made thankfully. 
In VS Code looking for suggest changes, clicking the dropdown ended up requesting a review. Where on GitHub.com they are buttons with a preview 🙀

![image](https://github.com/CosmosContracts/council/assets/18357827/17e88d35-822f-46e9-a0ff-77dd176a97de)

2024-05-10 22:18 UTC, kopeboy approved these changes

2024-05-10 22:26 UTC, poroburu commented on departments/development/statements/proposal_349/DRAFT-statement-20240510-01.md
> +The Juno Commonwealth Development Department respectfully recommends rejecting Juno Proposal #349, emphasizing the importance of aligning proposed initiatives in a collaborative and good faith with o
```suggestion
The Juno Charter Development Department respectfully recommends rejecting Juno Proposal #349, emphasizing the importance of aligning proposed initiatives in a collaborative and good faith with ongoing efforts being carried out by the Development Department.
```

2024-05-10 23:48 UTC, poroburu commented on departments/development/statements/proposal_349/DRAFT-statement-20240510-01.md
> +The Juno Commonwealth Development Department respectfully recommends rejecting Juno Proposal #349, emphasizing the importance of aligning proposed initiatives in a collaborative and good faith with o
Suggestion appended onto statement rebase below.

2024-05-10 23:51 UTC, poroburu commented
My changes are ready for review now in case the PR still does not like my previous request😺

2024-05-11 00:42 UTC, rayraspberry commented
I corrected some grammar and added a line to make clear that communication with Dev Dept should be considered public.

2024-05-11 02:33 UTC, poroburu approved these changes

2024-05-11 02:34 UTC, poroburu commented
Re-requesting kopeboy's stale review. LGTM.

2024-05-11 17:46 UTC, merged